### ISSUE TITLE
Different Builder behaviour between 0.6.6 and 0.7

### ISSUE THREAD

**Issue by kellerkind84** [vandeseer/easytable#100]
Hi,

awesome library, but I have a small issue: In 0.7 is an issue on the AbstractCellBuilder where the sequence of methods actually matters:

TextCell.builder()
.paddingLeft( 0.2 )
.settings( cellSettings( 0.1 ) ) // for borderwidth
.build();

actually does nothing to set the border width. The moment I set any kind of attribute before the settings, an empty settings object is initialised and does not get overwritten later. I have not checked, but I believe this behaviour to have shown only in 0.7, since our old code worked fine before. In any case, this behaviour is in my opinion heavily misleading...

best regards,
Kai

**Comment by vandeseer** [comment]
Thanks for reporting, Kai.

Can you check whether this has also shown in 0.6.6? 

There were definitely some changes in the settings (hence also the minor version change from 6 to 7), mostly to allow setting the border styles and widths separately if I am not mistaken. 

The question is what you want to achieve? 

Calling `settings(...)` directly shouldn't be necessary, everything can be done with the single options like `borderWidth(...)`or `paddingLeft(...)` etc. 

Best
Stefan

**Comment by vandeseer** [comment]
Did you finally change your code to not calling `.settings(...)` directly or did the problem not persist? 

Anyway: I am planning to remove access to `.settings(...)` for one of the next releases. It was never supposed to be exposed in the first place but it rather slipped through by not paying enough attention when using Lombok ... 😄
