### ISSUE TITLE
I have upvoted the StackOverflow thread, but I still want to donate

### ISSUE THREAD

**Issue by Adriansun** [vandeseer/easytable#102]
Title + what to do?

**Comment by vandeseer** [comment]
Hey @Adriansun, 

thanks for upvoting and I am more than happy you want to donate! 😃 
You can use PayPal for donating: paypal.me/SDeser 

Best
Stefan

**Comment by Adriansun** [comment]
I donated. Thank you for your work.

**Comment by vandeseer** [comment]
Thank you very much!
This is the first time someone donated for my Open Source engagement.

I am truly honored! 😃
