### ISSUE TITLE
Blurry Image in pdfbox 2.0.20

### ISSUE THREAD

**Issue by al-droid** [vandeseer/easytable#105]
Hi as described [here,](https://issues.apache.org/jira/browse/PDFBOX-4863)
and in many stackoverflow post, there was a regression in image rendering in version 2.0.20 solved in 2.0.21 released this summer.

[Release Note pdfbox 2.0.21](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310760&version=12348324)

I've tried compiling easytable with the 2.0.21 but I couldn't execute tests correctly because of this expection

> [ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found
> org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta; received 404 -- resource not found

neither -DskipTests helped me

> [ERROR] Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta
> org.owasp.dependencycheck.data.update.exception.UpdateException: Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta

Maybe i've missed some guidelines, 
:)

**Comment by vandeseer** [comment]
Hi @al-droid, 

the `develop` branch of easytable is using pdfbox 2.0.21. Also a new release with this (and other small) updates will come soon. So what you can do in the meantime is to git clone the repo, checkout the develop branch and then run

    mvn clean install -DskipTests -Dgpg.skip -Ddependency-check.skip=true

The messages stem from a vulnerability analysis which is automatically triggered if you don't disable it. 
If that run through you will have a version 0.7.2-SNAPSHOT in your local maven repo which you can then reference in your code.

What you can do as well is to explicitly exclude the pdfbox dependency from easytable and setting the 2.0.21 version explicitly in your own dependencies. 

Let me know if this helps
Stefan

**Comment by vandeseer** [comment]
Hello @al-droid,

there is a now version out now (0.8.0) which comes with pdfbox 2.0.21. 
So no need for workarounds or hacks anymore 😉 

Again, let me know if your issue is solved or alternatively just close the issue if this is the case. 

Best,
Stefan

**Comment by al-droid** [comment]
Hi vandeseer i was not aware of the vulnerability analysis. I will keep in mind next time I want to collaborate in this project :)

Also thank you for the kindly suggestions, I was using the library exactly that way, but now we have 0.8.0 :)

I will update my dependencies and I'll let you know, I think we can close this now.
