### ISSUE TITLE
Ability to modify a table after the PDF has been saved

### ISSUE THREAD

**Issue by smileatom** [vandeseer/easytable#108]
Hi, 
Seems like a great library, Im curious if I have a template pdf doc and I want to have tables with header rows as placeholders, is there a way to load a saved PDF and get a reference to the table object(s) in a page?  Not sure if there's a way to do that without this being integrated into the PDFBox metamodel.  But it would be very useful for templates to be able to have a table with set styles and then have a document renderer identify those tables as objects and add data rows to them without necessarily adding all the style information for each row.

Thanks and great job on this!

**Comment by vandeseer** [comment]
Hi @smileatom,

I think I get your point but this unfortunately not feasible. There is no notion of a table produced by this library that could be easily saved and restored in a PDF file. I guess it could somehow be done by utilizing some meta data. But it's nothing which should be incorporated into easy table but would need to be implemented "on top".

Best, 
Stefan

**Comment by smileatom** [comment]
I kind of figured, I have little knowledge of how these documents are created at a fundamental level, and no time to dig in further.  Thanks for your reply.  Did you see my question on why I cant break a page in the middle of a row instead of pushing the next row onto the next page?  Thanks and nice job on this!
