### ISSUE TITLE
Fill cell with hex code color

### ISSUE THREAD

**Issue by NtsCiccio** [vandeseer/easytable#120]
Hi, is possible to fill a Cell with an hex code color?

**Comment by vandeseer** [comment]
You can use `Color.decode` for that: 

    TextCell.builder()
      .text("...")
      .textColor(Color.decode("#ff00ff"))
      .backgroundColor(Color.decode("#111111"))
      .build()`

**Comment by NtsCiccio** [comment]
thanks again, is there another way to contact you without opening issues?

**Comment by vandeseer** [comment]
Hey, I suggest opening a question on stackoverflow tagging it with pdfbox and maybe mentioning easytable in the title or so. Then others can answer as well and the solution can be found easily, too.
