### ISSUE TITLE
ralfstuckert/pdfbox-layout 1.0.0 dependency build error in Jitpack repo

### ISSUE THREAD

**Issue by grasshopper7** [vandeseer/easytable#123]
Refer to the below links of folks pointing this out.

https://github.com/ralfstuckert/pdfbox-layout/issues/88
https://github.com/jitpack/jitpack.io/issues/4490
https://github.com/grasshopper7/extentreports-cucumber6-adapter/issues/36

The jar is also available in Mulesoft repository (https://repository.mulesoft.org/nexus/content/repositories/public/com/github/ralfstuckert/pdfbox-layout/ and https://mvnrepository.com/artifact/com.github.ralfstuckert.pdfbox-layout/pdfbox2-layout/1.0.0). Just need to add this repository declaration instead of Jitpack.

```
<repositories>
	<repository>
		<id>mulesoft-releases</id>
		<name>MuleSoft Repository</name>
		<url>https://repository.mulesoft.org/nexus/content/repositories/public/</url>
	</repository>
</repositories>
```

**Comment by vandeseer** [comment]
Thanks for pointing that out @grasshopper7 !

**Comment by vandeseer** [comment]
I added a hint to this issue to the README file. Hence I'll close it now.

**Comment by grasshopper7** [comment]
The author has released a new version on jitpack fixing this issue. https://github.com/ralfstuckert/pdfbox-layout/issues/88
