### ISSUE TITLE
Question about: WARNING: Modifying the current transformation matrix is not allowed within text objects

### ISSUE THREAD

**Issue by jrojasgon** [vandeseer/easytable#134]
Hi @vandeseer , I was wondering if there is a way for the lib to avoid logging this WARN errors? which come around normally when there is a specific Horizontal Alignment.

You can see the warns when executing https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/integrationtest/ParagraphCellTest.java

`WARNING: Modifying the current transformation matrix is not allowed within text objects`

**Comment by vandeseer** [comment]
Hi @jrojasgon,

for the "paragraph cells" everything's a bit difficult: Those are just wrappers around the pdfbox-layout library which is not developed any further. It could easily be the case that those stem from that library (I didn't have a closer look yet to be honest). In that case there's no chance in fixing it besides not using this type of cell ... 😉 

Hope this helps,
Stefan
