### ISSUE TITLE
Question: Treat A4 as split page and overflow narrow tables on same page

### ISSUE THREAD

**Issue by ParvatiD** [vandeseer/easytable#135]
I need to treat A4 page as 2 parts. The table width is never going to be 50% of the page in my requirement.
I wanted the table to be overflown to remaining part of the same page.
It is like treating A4 sheet as 2 pages split vertically.
I am attaching a sample for reference.
I wanted to know if this is possible?

[SplitPageTable.pdf](https://github.com/vandeseer/easytable/files/7279787/SplitPageTable.pdf)

**Comment by vandeseer** [comment]
Hi @ParvatiD 

I think that should be possible. You would most probably need to create a custom `TableDrawer` for that though.

**Comment by vandeseer** [comment]
For instance it would work with this custom `TableDrawer`: https://gist.github.com/vandeseer/5c30e093a197efcf55b4ba22090a1c63

**Comment by ParvatiD** [comment]
Apologies if this sounds like a beginner question.
How to enforce extended TableDrawer's draw method?
As my call is still invoking base TableDrawer's draw().

				OverflowOnSamePageTableDrawer.builder().page(page).contentStream(contentStream).table(table)
						.startX(PADDING).startY(startY).endY(PADDING).build()
						.draw(() -> document, () -> new PDPage(PDRectangle.A4), PADDING);

**Comment by ParvatiD** [comment]
Thanks @vandeseer. This worked perfectly for me. Appreciate your effort for considering this question as a requirement and getting it implemented.
