### ISSUE TITLE
Possible to add table created from easy table into PDF created using Ralf Stuckert's PDFBox-Layout?

### ISSUE THREAD

**Issue by arjitm786** [vandeseer/easytable#140]
Hi @vandeseer 

I'm working on a project and have created PDF using Pdfbox-layout by  Ralf Stuckert's. I see that this library also uses it uder the hood. Is there any way to add the table from this library into document of Pdfbox-layout?

Edit: or save table as image?

Thanks for the library and your work.
Regards.

**Comment by vandeseer** [comment]
Hello @arjitm786, 

I didn't try this by my own so far, but I think that shouldn't be too big an issue. 
Did you try it already? Have there been problems? If so, maybe just share an example ... 

Best,
Stefan

**Comment by arjitm786** [comment]
Hello @vandeseer ,

First of all, thanks for the reply. I've created TableElement, similar to ImageElement.java in rts.PDFBox, which draws table form this library and then can be added to rts PDFBox document. I want it to span to multiple pages, but the outcome is not as expected. If table height is 

1.  less than available space on current page , it works fine (success.pdf).
2.  greater than available space but less than Page.height, then buggy behavior (buggy.pdf).

I think this is because of the way PDFBox layout renders the element.
Since you've worked on PDFbox, I was hoping you can provide a solution.

[success.pdf](https://github.com/vandeseer/easytable/files/7631735/success.pdf)
[buggy.pdf](https://github.com/vandeseer/easytable/files/7631770/buggy.pdf)
[TableAdapterRunner.txt](https://github.com/vandeseer/easytable/files/7631776/TableAdapterRunner.txt)
[TableElementEasyTable.txt](https://github.com/vandeseer/easytable/files/7631777/TableElementEasyTable.txt)
[ImageElement.txt](https://github.com/vandeseer/easytable/files/7631780/ImageElement.txt)
