### ISSUE TITLE
[Bug / Update] Cannot make PDF with certain characters

### ISSUE THREAD

**Issue by Adriansun** [vandeseer/easytable#147]
Hello again,

I was wondering if the issue has been resolved with some characters not found / crash? Will Apache PDFBOX 3.0 solve this issue? Is there any font to use for this not to happen? I really like easytable. Good work.  All I need is for this issue to be resolved.

Reference
https://github.com/vandeseer/easytable/issues/130
https://github.com/vandeseer/easytable/issues/38
https://gist.github.com/vandeseer/46271f3e103e336b609edca4234dd4af
https://pdfbox.apache.org/

**Comment by Adriansun** [comment]
Maybe you are on vacation? Would like to have a reply, please.

**Comment by vandeseer** [comment]
Hey @Adriansun,

I'm not on vacation. This library has entirely been built in my spare time without being paid. It's a courtesy of mine to open the source code and let everyone use it for free. Not quite sure if we were on the same page here.

As I said already at the other issues this is not a problem of easytable but a problem of pdfbox. And actually I think it's not even a problem of pdfbox directly but of the fonts used. I'm not quite sure, but I think you just need to find a proper font. Please just ask e.g. at stackoverflow.com or at another public Q&A forum. This has nothing to do with easytable per se. 

Best,
Stefan

**Comment by vandeseer** [comment]
Maybe have a look e.g. here: https://stackoverflow.com/questions/57450039/printing-chinese-characters-in-pdfbox

Could be a good starting point.

**Comment by c4da** [comment]
> Maybe have a look e.g. here: https://stackoverflow.com/questions/57450039/printing-chinese-characters-in-pdfbox
> 
> Could be a good starting point.

Hi, Im pretty sure its not a problem of both pdfbox and easy table. You need to compose your own ttf file or find one that has all of your chars.

**Comment by c4da** [comment]
> Hey @Adriansun,
> 
> I'm not on vacation. This library has entirely been built in my spare time without being paid. It's a courtesy of mine to open the source code and let everyone use it for free. Not quite sure if we were on the same page here.
> 
> As I said already at the other issues this is not a problem of easytable but a problem of pdfbox. And actually I think it's not even a problem of pdfbox directly but of the fonts used. I'm not quite sure, but I think you just need to find a proper font. Please just ask e.g. at stackoverflow.com or at another public Q&A forum. This has nothing to do with easytable per se.
> 
> Best, Stefan

Hi, Im pretty sure its not a problem of both pdfbox and easy table. You need to compose your own ttf file or find one that has all of your chars.

**Comment by Adriansun** [comment]
I agree with you. It seem to be a font issue. There are several problems with the fonts. Let us start from the start.

Information / Request:
I want to let Japanese, Russians, Thai... create a PDF.

Question 1:
What font has UTF-8/everything and is free?*
* I looked at FreeSerif, but it will crash with Korean characters. 

Question 2:
If there is no UTF-8 font to use then can there be an option which enables a try-catch to catch all odd letters and just show an "X" on that character position?

Looking forward to your answer.

**Comment by Adriansun** [comment]
Can we have a good tutorial where this all in one font exists that can express all characters, please?

**Comment by Adriansun** [comment]
Can we have a good tutorial where this all in one font exists that can express all characters, please? A code example would be great.
