### ISSUE TITLE
ParagraphCell support in easytable 1.0?

### ISSUE THREAD

**Issue by zhangwx2020** [vandeseer/easytable#163]
Dear Sir,
Could you add back ParagraphCell support in in easytable 1.0 for PDFBox 3.X?
Thanks,
Bill

**Comment by vandeseer** [comment]
Unfortunately that's not possible since it was wrapping another library that is not able to deal with PDFBox 3.x. Since that library is not maintained anymore I had to remove it. 
Best,
Stefan
