### ISSUE TITLE
Question: Is this library still actively being developed / maintained?

### ISSUE THREAD

**Issue by Lolf1010** [vandeseer/easytable#164]
Hi,
at work we are currently looking info the generation of pdfs that could include tables.
So i was wondering if your project is still actively being developed / maintained.
I see activity in the issues. Has been a couple weeks since the last coding-activity - but maybe thats just because the library is working fine :)

Thanks.

**Comment by vandeseer** [comment]
Hey @Lolf1010,

I try to keep the dependencies up to date, but I'm not adding new features. If you're using it at work, feel free to contribute. Be it with a PR or by paying me a beer ;)

Cheers,
Stefan
