### ISSUE TITLE
Latest release contains a logback.xml

### ISSUE THREAD

**Issue by Yopi** [vandeseer/easytable#168]
It looks like the last release added a logback.xml configuration, this overrides logging in our application. I'm not sure if that was intentional? And if it was it should probably be added to the release notes.

https://github.com/vandeseer/easytable/commit/db55cee99ee22e0ac1b448416a7f2a5d7472b557

**Comment by vandeseer** [comment]
I guess it was only semi intentional: a version upgrade from a dependency led to trillions of log messages when building this library. I added the logback.xml file in order to silence it, but I think it should have ended in the tests related folder.

Thanks for reporting, will have a look soon

**Comment by vandeseer** [comment]
Fixed it now.

**Comment by Yopi** [comment]
Thank you!
