### ISSUE TITLE
Allow header row to be added on each page for multi-page tables

### ISSUE THREAD

**Issue by vandeseer** [vandeseer/easytable#27]
If a table is drawn over several pages the header row should be shown on top of each new page.

This should be configurable, e.g. in the builder for `TableDrawer`.

Also see: https://stackoverflow.com/questions/54233886/pdfbox-header-in-all-pages-using-easytable

**Comment by istiti** [comment]
Just discover this nice lib, how can we know  we can’t add row and break page?

**Comment by vandeseer** [comment]
Please have a look at this example: [TableOverSeveralPagesTest.java](https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/integrationtest/TableOverSeveralPagesTest.java#L56)

The basic idea is to set the `endY` value in the `TableDrawer` that defines when it has to stop drawing.
You can also check the answer on the link to the stackoverflow question mentioned above.

**Comment by istiti** [comment]
@vandeseer thank you. Already check this example but as you said there is endY() but in do{...}while there is another breaking  page manager. Is both needed? It is a little out of scope to me. 
Another requirement for me would be how can i know in advance if multiple rows (2 or 3) could be drawed  to keep them together thank you

**Comment by vandeseer** [comment]
What are trying to achieve exactly @istiti? 

But yes, you need both: 
- Some kind of "managing the pages" (i.e. setting the content stream on every new page on the table drawer)
- The definition where on the page the limit is reached so that the drawing is continued on the next page (i.e. the `endY` value)

Regarding that `endY` value you will need to do some calculations on your own, depending on your requirements, I guess.

**Comment by istiti** [comment]
@vandeseer tank you for consideration!
im talking about these two requirements:
1. im trying to achieve this [repeat header+subHeader](https://drive.google.com/open?id=1psBUukZq1_scaT4_gposYnWKq9k29-8T) here you can see header + subHeader "Switzerland" is repeated,

2. then this[ grouped-rows](https://drive.google.com/open?id=1lFLgZlqwnYOr-3lAv52PV6KxG3xTQaA_) feature, here you can see I want keep together subHeader or second-level like here Ana...

Hope you understand yet :)

**Comment by vandeseer** [comment]
Ouh, that's a little bit more involved ;) If I find some time in the next days I can have a look, but don't expect too much. In theory you should be able to implement it by extending the `TableDrawer` class and adapt the relevant methods to your needs.

**Comment by plpanda** [comment]
I hope including the Header at the top of the table in every page is not included. How can we improve that ?  Any Suggestions ...

**Comment by vandeseer** [comment]
For drawing the header repeatedly on every page the subclass looks as follows (will be included in the next relesae): [HeaderTableDrawer.java](https://github.com/vandeseer/easytable/blob/develop/src/main/java/org/vandeseer/easytable/RepeatedHeaderTableDrawer.java)

@istiti You would need to adapt it a bit so that a 2nd header row is added. Could you provide me with the table structure you already got? So maybe I can help you to add it ;) 

@plpanda The adapation I mentioned will be included in the next release, but still you could use it already by including that class into your project. Does this help you?

**Comment by istiti** [comment]
@vandeseer thank you a lot considering my feature request. TBH it is a little out of scope to me. I propose two features :
1. Grouped rows
2. Repeat header and subheader 

Which on your code cover? 

And what you think to use this simple table with two column and fake data  I uploaded above to get a try? 

This is our requirement if I succeed with your lib I can definitly choose it in our project so thank you in advance

**Comment by vandeseer** [comment]
The code above covers the repeated header (no subheader though). If time allows I can also sketch a version with subheaders being repeated as well. 

For the grouped rows you could just use row spanning, because then the page will break if a row doesn't fit on the page anymore; example code: https://pastebin.com/jCerBU99

**Comment by vandeseer** [comment]
Repeated headers on every new page is now possible with version 0.4.3. Hence I will close this issue.

**Comment by etorrenti** [comment]
What if I'd like to start drawing a multi-page table after a block of text? Due to the pageSupplier invocation, a new page is added as soon the table starts. Thanks
