### ISSUE TITLE
Infinite draw loop bug

### ISSUE THREAD

**Issue by unknownzone96** [vandeseer/easytable#28]
When a cell in the table of the drawer has text that exceeds the length of the page, then the draw() method never finishes. Edit the TwoPagesTableTest integration test 

public class TwoPagesTableTest {

    @Test
    public void createTwoPageTable() throws IOException {
        final Table.TableBuilder tableBuilder = Table.builder()
                .addColumnOfWidth(200)
                .addColumnOfWidth(200);

        CellText dummyHeaderCell = CellText.builder()
                .text("Header dummy")
                .backgroundColor(Color.BLUE)
                .textColor(Color.WHITE)
                .borderWidth(1F)
                .build();

        String longText = "Sed turpis nisl, ullamcorper vitae ornare eget, porta ac odio. Nunc lacinia convallis urna sit amet scelerisque. Morbi neque est, tempor sit amet sagittis in, luctus et nisl. Phasellus ut mollis felis. Sed viverra tortor in ligula ultricies, quis faucibus turpis varius. Duis ante leo, ornare sed lectus in, finibus placerat est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus rhoncus felis sit amet ex consequat aliquam. Ut euismod odio iaculis vulputate malesuada. Donec euismod ipsum id erat ullamcorper elementum. Aenean malesuada mattis libero ac pretium. Nam non tempor risus, in congue turpis. Nam mi dolor, gravida ac imperdiet quis, pulvinar sed metus. Sed tempor orci magna, non aliquet nisl posuere vitae. Cras erat felis, euismod et sodales cursus, fermentum at arcu. Aenean maximus magna vel dignissim ullamcorper.Sed turpis nisl, ullamcorper vitae ornare eget, porta ac odio. Nunc lacinia convallis urna sit amet scelerisque. Morbi neque est, tempor sit amet sagittis in, luctus et nisl. Phasellus ut mollis felis. Sed viverra tortor in ligula ultricies, quis faucibus turpis varius. Duis ante leo, ornare sed lectus in, finibus placerat est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus rhoncus felis sit amet ex consequat aliquam. Ut euismod odio iaculis vulputate malesuada. Donec euismod ipsum id erat ullamcorper elementum.";

        CellText dummyCell = CellText.builder()
                .text("dummy")
                .borderWidth(1F)
                .build();

        CellText bigCell = CellText.builder()
                .text(longText)
                .borderWidth(1F)
                .build();

        tableBuilder.addRow(
                Row.builder()
                        .add(dummyHeaderCell)
                        .add(dummyHeaderCell)
                        .build());

            tableBuilder.addRow(
                    Row.builder()
                            .add(dummyCell)
                            .add(bigCell)
                            .build());

        final PDDocument document = new PDDocument();

        PDPage page = new PDPage(PDRectangle.A4);
        TableDrawer drawer = TableDrawer.builder()
                .table(tableBuilder.build())
                .startX(50)
                .startY(page.getMediaBox().getHeight() - 50)
                .endY(50F) // note: if not set, table is drawn over the end of the page
                .build();

        do {

            document.addPage(page);
            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                drawer.contentStream(contentStream).draw();
            }
        } while (!drawer.isFinished());

        document.save("target/twoPageTable.pdf");
        document.close();
    }

**Comment by vandeseer** [comment]
Hi @unknownzone96, thanks for reporting this! 

I will have a look (as soon as I find some free time for it).

**Comment by vandeseer** [comment]
I am still not sure how to deal with that, but I think I will add an exception that is thrown as soon as it's clear that the drawing will inevitably run into this infinite loop. Solutions like automatically splitting the text or similar are just too complex to implement given the frequency this is expected to happen.

**Comment by vandeseer** [comment]
It should be fixed now in `develop` (with commit https://github.com/vandeseer/easytable/commit/9abcfce38d32208c186552ceefc92a239e5664d6)

**Comment by vandeseer** [comment]
Refactored the code a bit, but left the logic the same. So in the next release the fix will be included.
