### ISSUE TITLE
Publish to jcenter and maven repo 

### ISSUE THREAD

**Issue by RussoNC** [vandeseer/easytable#3]
Hello, first of all thanks for this amazing little lib. Do you think it would be possible for you to push this in jcenter and maven ? It would be easier for new versions and maintenance. 
Thanks again !

**Comment by vandeseer** [comment]
Hey @RussoNC , glad you like it! :) Currently I do not have much spare time, but since I realized now that at least one developer would like to have it in maven central I will take publishing into consideration ;) Will keep you posted. Cheers.

**Comment by RussoNC** [comment]
Sounds good man ! Happy coding ^^

**Comment by tkatz** [comment]
+1 Thanks for this nice little lib which is making live much easier :-)
I would also like to have this available in maven central / jcenter.

**Comment by AutJon** [comment]
How to add an image and text to the same cell?

**Comment by HolgerNeub** [comment]
+1 Maven would be great

**Comment by vandeseer** [comment]
Will close this now, since it's available now :) 

        <dependency>
            <groupId>com.github.vandeseer</groupId>
            <artifactId>easytable</artifactId>
            <version>0.3.0</version>
        </dependency>
