### ISSUE TITLE
Image not centered if row height modified by text

### ISSUE THREAD

**Issue by hooperbill** [vandeseer/easytable#32]
I have a row of cells and in one cell the text wraps causing the row height to increase. One of the cells contains an image and when this row height increase occurs the image is aligned to the bottom of its cell. Setting the vertical alignment to MIDDLE does not affect the image placement. 

[outputA.pdf](https://github.com/vandeseer/easytable/files/2896245/outputA.pdf)
[outputB.pdf](https://github.com/vandeseer/easytable/files/2896246/outputB.pdf)
[ImageCellSpan.java.txt](https://github.com/vandeseer/easytable/files/2896247/ImageCellSpan.java.txt)

**Comment by vandeseer** [comment]
Thanks for reporting @hooperbill! I will have a look as soon as a find a bit of time. Also I am always open for pull requests ... ;) 

Best,
Stefan

**Comment by vandeseer** [comment]
I created a branch with a fix: https://github.com/vandeseer/easytable/tree/issue32
Turned out that alignment was only implemented for text cells so far (I didn't really use this feature myself). 

So you could build that branch and use it already. For a release I want to add some more tests and refactor/tidy up the code a bit which I will do in the next days or rather weeks – depending on my spare time.

**Comment by hooperbill** [comment]
Many thanks! Will look for time to try out the develop branch.

**Comment by vandeseer** [comment]
Just released version 0.4.1 which should remedy this issue. Please let me know if it does not. And if you have some nice looking tables to share, please let me know! :smiley:

**Comment by hooperbill** [comment]
I was able to test version 0.4.1 and the image is correctly centered vertically. But the horizontal centering appears to now be broken. It appears that the image is centered on the image's left edge. This may be simply a math error that does not take the image width into account when calculating the cent.
[output.pdf](https://github.com/vandeseer/easytable/files/2953475/output.pdf)

**Comment by vandeseer** [comment]
A classic: The issue was that the image height was used where the image width should have been used. I didn't see it in the tests though, because I used a quadratic image ... :smile:
