### ISSUE TITLE
Row spanning affects image resizing in the next cel

### ISSUE THREAD

**Issue by hooperbill** [vandeseer/easytable#40]
I have two rows where the first cell of each row is spanning the two rows. The remainder of the cells in each row contains images. The first row of images is sized correctly, but the first cell of the second row will resize image in the first cell with the remaining cells in the row sized correctly.

If I disable the row spanning of the first cell all the images are sized correctly.

I have not found a possible work around.

![no row spanning](https://user-images.githubusercontent.com/16262444/56701200-b053bb00-66b2-11e9-866a-82fe88cd4e1f.png)
![row spanning](https://user-images.githubusercontent.com/16262444/56701204-b3e74200-66b2-11e9-9b30-33cc0e4e0f2c.png)

**Comment by vandeseer** [comment]
Interesting. Thanks for reporting! As soon as I find a bit of time (can possibly take a bit longer) I will have a look.

**Comment by vandeseer** [comment]
I could find the issue and committed a fix to the `develop` branch (https://github.com/vandeseer/easytable/commit/5c19f5e4555d976a05043808389660b892a08048). In the next days I will also release a new version. Thanks again for reporting!

**Comment by vandeseer** [comment]
The fix is released with version 0.4.3, I will hence close this ticket.

**Comment by hooperbill** [comment]
Many thanks!
