### ISSUE TITLE
Pagination not working properly for multiple tables with multiple pages

### ISSUE THREAD

**Issue by SagarKadu** [vandeseer/easytable#44]
How to draw multiple tables paginated across different pages using current lib..i.e. new table should be drawn next to existing one in paginated fashion

**Comment by vandeseer** [comment]
I will have a look to come up with a simple example as soon as I find some time for it. Maybe you can already share what you tried so far.

**Comment by SagarKadu** [comment]
I tried ExcelLikeExampleTest with 2 tables..as long as 2 tables have data within 1 page it works fine but if data grows over 1 page for any one of the table it breaks..I tried combining example of TableOverServeralPages with ExcelLikeExampleTest but it doesn't work properly

**Comment by vandeseer** [comment]
After having a closer look I think the easiest solution is to adapt the `TableDrawer` class a bit in the library. The idea is to add an additional member that stores the `y` value at the end, i.e. when drawing the table is finished.

**Comment by vandeseer** [comment]
The issue is fixed with release 0.5.1. One can now draw several multipage tables on the same document.

**Comment by arunmurukesh** [comment]
Unable to determine the Y coordinate for the second multipage table within same document, Table is being drawn with more space.

Please share me a working example if anyone has

**Comment by vandeseer** [comment]
Hey @arunmurukesh, please have a look at https://github.com/vandeseer/easytable/issues/59 – there is an example on how to do it.
