### ISSUE TITLE
Feature Request - Row spanning

### ISSUE THREAD

**Issue by Selikoff** [vandeseer/easytable#5]
Love the tool, but it would be helpful if it had row spanning.   The idea is that a cell could span two or more rows, with alignment of top/middle/bottom for the text that in it.  Would also be helpful if text within could be broken across multiple lines.

**Comment by vandeseer** [comment]
Thanks @Selikoff for the request; I currently don't have much time to develop besides work, so I cannot promise anything, but your plea is heard ;)

**Comment by vandeseer** [comment]
Row spanning is now implemented. Not yet though: vertical alignment and breaking text across multiple lines.

**Comment by vandeseer** [comment]
Breaking text is implemented, and vertical alignment is now tracked in this issue: https://github.com/vandeseer/easytable/issues/9

**Comment by egoossens** [comment]
Thanks for this library. I can't seem to understand how row spanning works. Can you point me to the methods I should use? Thanks!

**Comment by vandeseer** [comment]
Hey @egoossens, row spanning is indeed implemented but not yet released ... ;) 

It is still in the `development` branch: https://github.com/vandeseer/easytable/tree/develop (you will also find an example in the README, or just look here: https://github.com/vandeseer/easytable/blob/develop/src/test/java/org/vandeseer/integrationtest/ExcelLikeExampleTest.java#L117) – but I think I will release again in the next days (or weeks). If you want to use it right now you would need to check out that branch and `mvn clean install` it yourself.

Hope this helps! :)

**Comment by egoossens** [comment]
Thanks for getting back @vandeseer. I'm looking forward to the next release then (I'm having trouble using the develop branch in my Gradle project).

**Comment by vandeseer** [comment]
The release should be out now, version 0.4.0 @egoossens. I hope everything works as expected, let me know in case it does not. If you create some nice tables that you think are worth sharing, please also let me know ;)

**Comment by egoossens** [comment]
Thanks @vandeseer! Seems to work as intended... Nice work!
