### ISSUE TITLE
Questions regarding 0.6.0

### ISSUE THREAD

**Issue by INPUTsys-Chris** [vandeseer/easytable#59]
Hi,

imagine I want to add a table in a header section of a pdf. So I render the content area for all pages in the pdf and afterwards i want to render a table containing "Page x of 10" in the top area on every page.

This was not easy in 0.5.2 but I managed to subclass "TableDrawer" to not use the last page of the document every time draw() is called. In 0.6.0 this is not so easy anymore because of the refactorings. There should be a page supplier which is not only for new appended pages but for every existing page I want Easytable to render onto.

Are there plans supporting that kind of feature?

2nd question: is there an easy way to determine where the table ends? I mean, getting the y coordinate after adding the table.

Thank you

**Comment by vandeseer** [comment]
Hi @INPUTsys-Chris,

I am not sure if I understood your problem correctly, but one way to do that could be like so: https://gist.github.com/vandeseer/6758c76fc4070a5bddd016c4311bc359

Regarding your second question I will have a look on how to do that the easiest way. It should be possible. 

Best,
Stefan

**Comment by INPUTsys-Chris** [comment]
Hi Stefan,

thank you for your quick response.

Regarding the y-coordinate problem (question 2): I had a similar solution when using 0.5.2, overwriting drawBorders. Your solution works perfectly. Thank you

Regarding the header/footer solution: there were some bugs in my code like adding the page in pagesupplier to the document on my own. But the main problem was using:

**public void draw(Supplier<PDDocument>,Supplier<PDPage>,float)**

instead of just

**draw()**

when drawing the header/footer-table.

Both methods are completely different in choosing the page to be drawn on:

**draw()**: draw on the current page (set via .page and .contentStream)
**public void draw(Supplier<PDDocument>,Supplier<PDPage>,float)**: draw on the last page or a new page

With your explanation I could adapt my code and now it's working perfectly. My abstraction layer now differentiates between in-page table and header/footer tables.

Thank you

Chris

**Comment by vandeseer** [comment]
Glad I could help you. :smiley: 

Best,
Stefan
