### ISSUE TITLE
Table always gets added to the last page

### ISSUE THREAD

**Issue by Skiid** [vandeseer/easytable#61]
The table gets always added to the last page in my implementation.
Is there a way to add the copy of a table to each page? Would be handy to create footers or headers of a document.

``` 
val contentStream = PDPageContentStream(
            pdfDocument, pdfDocument.getPage(0),
            PDPageContentStream.AppendMode.APPEND, false, false
        )

        TableDrawer.builder()
            .table(table)
            .startY(yPos)
            .startX(tableRect.lowerLeftX)
            .contentStream(contentStream)
            .build()
            .draw(Supplier<PDDocument> { pdfDocument }, Supplier<PDPage> { PDPage(PDRectangle.A4) }, headerOffset)
```

**Comment by vandeseer** [comment]
That's possible, maybe have a look here: 
- https://github.com/vandeseer/easytable/issues/59
- https://gist.github.com/vandeseer/6758c76fc4070a5bddd016c4311bc359

Hope this helps!

Best,
Stefan

**Comment by Skiid** [comment]
Thanks thats exactly what i needed why isn't this the normal behaviour of the table drawer?

**Comment by vandeseer** [comment]
Actually it is! 😉 

Have a look at the [minimum working example](https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/MinimumWorkingExample.java) which is also referenced from the README for instance.

You can simply call `.draw()` and that's it.
