### ISSUE TITLE
How to increase image size when we do col span

### ISSUE THREAD

**Issue by Daya2006** [vandeseer/easytable#64]
Hi,

I have written a table with 4 columns but i have a requirement of that table to sometime display either two or one image in one of the rows. 
I do that by doing the col Span if one row then span col to 4 cells. else if two images then span two columns into two cells.
The only problem i am facing here is the size of the image which is coming its very small. 

When i create the Table of two columns and use the same image , the image is better but is there a way to increase the width of image in case of Col span as well?

below is part of my code for table and some of the if else conditions for image display:

Table.TableBuilder tableBuilder = Table.builder()
	            .addColumnOfWidth(145)
	            .addColumnOfWidth(145)
			    .addColumnOfWidth(145)
		        .addColumnOfWidth(145);

if (pdfImage5_4 && pdfImage5_6)
	        	{
	        		
	        		 tableBuilder.addRow(
	 		                Row.builder()
	 		                        .add(ImageCell.builder().image(image5_4).maxHeight(2000l).borderWidth(1).horizontalAlignment(HorizontalAlignment.CENTER).colSpan(2).build())
	 		                        .add(ImageCell.builder().image(image5_6).maxHeight(2000l).borderWidth(1).horizontalAlignment(HorizontalAlignment.CENTER).colSpan(2).build())
	 		                        .build());
	        	}

if (pdfImage5_4)
	        	{
		        	tableBuilder.addRow(
			                Row.builder()
			                        .add(ImageCell.builder().image(image5_4).borderWidth(1).maxHeight(2000l).colSpan(4).horizontalAlignment(HorizontalAlignment.CENTER).build())
			                        .build());
	        	}

if (!(pdfImage5_4) && pdfImage5_6)
	        	{
	        		tableBuilder.addRow(
	 		                Row.builder()
	 		                        .add(TextCell.builder().text(Constants.NOPREVIEWPREUPGRADE).font(TIMES_ROMAN).fontSize(6).borderWidth(1).colSpan(2).horizontalAlignment(HorizontalAlignment.LEFT).build())
	 		                        .add(ImageCell.builder().image(image5_6).borderWidth(1).maxHeight(2000l).horizontalAlignment(HorizontalAlignment.CENTER).colSpan(2).build())
	 		                        .build());
	        	}

**Comment by vandeseer** [comment]
Generally speaking you can just use the `.scale(...)` setting: 

    ImageCell.builder()
        .image(someImage)
        .borderWidth(1)
         ...
        .scale(1.5f)
        .build()

**Comment by Daya2006** [comment]
I tried scale option with different values (2f, 60f , 100f) but nothing worked , the image seems to be same still. tried removing the .maxHeight(2000l) option as well as with that but did not saw any different.
The only difference i can see is when i reduce the columns in the table  then i dont even have to mention the max ht or scale it shows the big image.  But my requirement for table is for some rows its 4 column so had to create 4 column table and then was doing a colspan for image

**Comment by vandeseer** [comment]
Alright. I will have a look.

**Comment by Daya2006** [comment]
thanks

**Comment by vandeseer** [comment]
Yep, this is a bug. It's super easy to fix and I will release a new version within some days (depending on my free time). In case you need a fix very quickly you could simply subtype the image cell and change the line 41 from: 

    final float resultingWidth = getColumn().getWidth() - getHorizontalPadding();

to: 

    final float resultingWidth = getWidth() - getHorizontalPadding();

**Comment by vandeseer** [comment]
This is fixed now with release 0.6.1.
