### ISSUE TITLE
Do we have an example where table data can span across multiple pages

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#65]
I have a business need where I need to span data across multiple PDF pages. e.g. I have expense data which could have more than 100 rows. in this case i have to split the data across multiple pages.

![image](https://user-images.githubusercontent.com/24460200/74773148-f6d46080-5256-11ea-9886-866f7f143d7b.png)

**Comment by vandeseer** [comment]
You mean like so: https://github.com/vandeseer/easytable#can-i-draw-a-table-over-multiple-pages ?

**Comment by vikramtambe** [comment]
Thanks... If you see in my example I would also like to draw header as well as footer data along with rest of the table data.

**Comment by vandeseer** [comment]
Well, there is a drawer for repeating headers (also see: [here](https://stackoverflow.com/questions/54233886/pdfbox-header-in-all-pages-using-easytable/60100581#60100581)). 

Regarding a repeated footer: Does it have to be part of the table? If so, you would need to implement a table drawer for yourself. But maybe you can just simply do this outside of the table. I didn't fully understand what exactly has to be present in the footer.

**Comment by vikramtambe** [comment]
anyway I found the solution to add footer to each page. footer is not part of table.

**Comment by vandeseer** [comment]
Alright. I will close this issue.
