### ISSUE TITLE
How to make the font bold in case i use a font other than specified in PDFBOX

### ISSUE THREAD

**Issue by Daya2006** [vandeseer/easytable#68]
Hi,

I am trying to use a different font which is not part of default pdfbox. so loading the ttf file for that font and adding modifying the contentstream to use that font.
but i am not able to make the font bold where needed in tables. like some columns require bold for the same font and some does not. can you tell me if its possible to bold the font (without using existing fonts like times bold) etc

**Comment by vandeseer** [comment]
Have a look at this thread on stackoverflow: 
- https://stackoverflow.com/questions/21561298/pdfbox-same-stream-with-bold-and-normal-text
- this gist illustrates how to use it in easytable: https://gist.github.com/vandeseer/d5c8ac342e52cbfa521ce0a55849b7e4

As said in the answer of the linked stackoverflow post: 

> The preferable way for creating bold (or otherwise styled) text is to use a font variant which has been created explicitly for that variant.
