### ISSUE TITLE
easytable example where I can include nested rows in a table based on data

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#69]
I have  a requirement where I need to add dynamic rows to existing table if nested data exists. 
e.g. I have parent note and people can reply to parent node which will become a child note. people can reply to child note etc.

![image](https://user-images.githubusercontent.com/24460200/75073909-17532380-54c0-11ea-8127-5f3a086635dd.png)

**Comment by vikramtambe** [comment]
As of now i am able to generate table which will have only one parent note. Trying to figure out solution where i can added replies to parent node within same row. please let me know your comments.

**Comment by vandeseer** [comment]
Sorry @vikramtambe, but from my point of view this is nothing specific to easytable but a general programming question of yours. Therefore I would suggest to ask this question on a programmer's forum like stackoverflow. 

In theory you can also create recursive structures by using a table within a table cell like so: https://stackoverflow.com/questions/59959873/pdf-easytable-may-i-insert-table-within-cell/60101301#60101301
