### ISSUE TITLE
first 2 or 3  rows for table header

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#70]
Do we have a way to add first 2/3 rows for header. I have requirement where I would like to repeat first 3 rows on each page while drawing table data. please let me know  your comments.

**Comment by vandeseer** [comment]
Well, I hacked together a simple example illustrating the case of three repeated header rows: 
- https://gist.github.com/vandeseer/8c2ca07265dc44873eeb5ead64b37dd7

I even may change the current implementation of the regular table drawer that repeats header rows to have it configurable and being part of the regular easytable API.

**Comment by vandeseer** [comment]
The number of rows to repeat can now be set on the `RepeatedHeaderTableDrawer` (fixed in version 0.6.2).
