### ISSUE TITLE
How to draw text or small rectangle within ImageCell

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#71]
I have a requirement where I need to draw text or small rectangle/circle/square within imageCell. 
PS - the data will be dynamic... please see below sample images which i am trying to build. As of now I am able to add background images as ImageCell is easytable. 

Please let me know your inputs. 
e.g
![image](https://user-images.githubusercontent.com/24460200/75460267-e0a95d00-5946-11ea-932f-bf17d5625d95.png)

![image](https://user-images.githubusercontent.com/24460200/75460323-f28b0000-5946-11ea-9f57-8e1aef7c42e4.png)

**Comment by vandeseer** [comment]
You would need to do it the same way as in https://github.com/vandeseer/easytable/issues/60: Create a custom cell type (in this case you would need to extend `ImageCell`) and build your custom functionality on top of what the base classes already provide you with.
