### ISSUE TITLE
Different Font and Font Size within single TextCell

### ISSUE THREAD

**Issue by vikramtambe** [vandeseer/easytable#72]
I would like to use different font and font size within Textcell.

Please let me know your comments.

e.g.
![image](https://user-images.githubusercontent.com/24460200/75462516-fe2bf600-5949-11ea-8889-a6415f9c2b73.png)

**Comment by vandeseer** [comment]
Have you read the README: https://github.com/vandeseer/easytable#paragraph-cells?

**Comment by vikramtambe** [comment]
Thanks... I dont know how I missed it..

**Comment by vandeseer** [comment]
No worries. But I will close this issue now.
