### ISSUE TITLE
Cannot use in Android because of awt classes

### ISSUE THREAD

**Issue by royale1223** [vandeseer/easytable#76]
Since this library uses `java.awt.*` classes, which isn't a part of Android, it's impossible to use it inside an Android Project. Please consider removing dependency on awt classes and making the library Android complaint.

**Comment by vandeseer** [comment]
The problem is that the underlying library (which is Apache PDFBox) uses those dependencies. So this is unfortunately nothing that can be fixed within easytable.

**Comment by krprashant94** [comment]
Please make an alternate by using  [PdfBox-Android](https://github.com/TomRoush/PdfBox-Android) or [VivyTeam - pdfbox-android ](https://github.com/VivyTeam/pdfbox-android)
