### ISSUE TITLE
Wrong linebreaking

### ISSUE THREAD

**Issue by AndreKoepke** [vandeseer/easytable#81]
Hi @AndreKoepke, 

there's still an issue here. Didn't see that the first time unfortunately. Please have a look again at the "excelLike.pdf" file: In the last line on the cell on the right, the line should not be justified and what is of more importance: the second to last cell in the middle has a strange line breaking – just compare this with the image in the README file. 

I am currently working on an automatic comparison of the generated PDF files so that such differences will be detected early on and not only by having a look manually ... 
As soon as I'm done I will put all the generated files from the latest version before this change under version control and we will hopefully see that there's a change in the rendered PDF documents. 

Best,
Stefan

_Originally posted by @vandeseer in https://github.com/vandeseer/easytable/pull/79#issuecomment-599201065_

**Comment by AndreKoepke** [comment]
I found the error. If there is only a dot or something as first char, then it breaks.

**Comment by AndreKoepke** [comment]
And found the other bug. With my new wordbreak-algo it shows up. Fix is on the way.

**Comment by AndreKoepke** [comment]
First bug:
![image](https://user-images.githubusercontent.com/15613049/76704368-d6be8280-66d8-11ea-8ca7-df49dbb82043.png)

Second bug:
![image](https://user-images.githubusercontent.com/15613049/76704373-e63dcb80-66d8-11ea-8bca-6a7d5e75d696.png)

**Comment by AndreKoepke** [comment]
Now there is something wrong with the cells-background. But I have no idea what's going wrong.
@vandeseer can you have a look? 
![image](https://user-images.githubusercontent.com/15613049/76704544-fc985700-66d9-11ea-9d70-c40c93c7db28.png)



(I wrote it in a old-version of easytable, because we are using the old version in a project)

**Comment by vandeseer** [comment]
Thanks for your effort @AndreKoepke! 

I changed the files accordingly on the current `develop` branch. Also did I check the issue with the background: It doesn't happen on the most recent version, so that's fine :+1: :smiley: 

I will close this issue as soon as I have released the new version.

**Comment by vandeseer** [comment]
Version 0.6.3 is published now.
