### ISSUE TITLE
.getFinalY()

### ISSUE THREAD

**Issue by buzzer83** [vandeseer/easytable#83]
Hi, I have tried the new functionality of the final position of the table. If it is used on a standard table it works perfectly. If it is used on a repeated table the method correctly returns the position y but not the page of the document where the table ends. Are you planning to implement this too? Thank you for your work.

**Comment by vandeseer** [comment]
I didn't yet think about it. It should be absolutely simple to implement. So most probably I will implement it in one of the next releases. Also I am always open for pull requests :wink:

**Comment by vandeseer** [comment]
This was implemented in the meantime and is released. Will close hence.
