### ISSUE TITLE
DrawingUtil#drawRectangle calls closePath() when path already got closed by preceding fill()

### ISSUE THREAD

**Issue by msww** [vandeseer/easytable#85]
Hi - I'm trying out easytable for a project, and am finding that some PDF processors (e.g. `pdftotext` from Poppler 0.48.0) spit out large numbers of messages like `Syntax Error: No current point in closepath` on documents I create using easytable. 

It looks like the cause is that [DrawingUtil#drawRectangle calls closePath()](https://github.com/vandeseer/easytable/blob/2bddd60e4c1276ee3d8865b9ffbf942c31644ca4/src/main/java/org/vandeseer/easytable/drawing/DrawingUtil.java#L38
) (which maps to PDF content stream operator `h`) as part of drawing the rectangle. However, this happens after it has already called fill(), which is implemented as PDF's operator `f`. 
According to the [PDF Specification PDF 32000-1:2008 section 8.5.3.3.1](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G7.3901540), the `f` operator already closes any open subpaths, leaving no open path that could be closed.

I think the call to closePath() is redundant. Removing the line results in a PDF file that does not cause those error messages without any obvious change to the rendering of the table.

**Comment by vandeseer** [comment]
Hey @msww , thanks a lot for your thorough analysis! 

I never experienced any issue like the one you are mentioning but your comment makes perfect sense. I will hence remove the respective line (as soon as I find time and if there are no other issues popping up due to removing the line).

Thanks again!

Best,
Stefan

**Comment by vandeseer** [comment]
Removed the respective line in version 0.6.5. If you find anything else, let me know!
