### ISSUE TITLE
paragraph underline markup not working

### ISSUE THREAD

**Issue by stanleyfl88** [vandeseer/easytable#86]
tableBuilder.addRow(Row.builder()
                    .add(ParagraphCell.builder()
                        .lineSpacing(1.2f)
                        .colSpan(6)
                        .horizontalAlignment(HorizontalAlignment.JUSTIFY)
                        .paragraph(Paragraph.builder()
                             .append(Markup.builder()
                                     .markup(
                                             "Test `__underline__`"
                                     )
                                     .font(Markup.MarkupSupportedFont.HELVETICA)
                                     .build()
                              )
                             .build())
                        .build())
            .build());

**Below are libraries included**
pdfbox-2.0.19.jar  
pdfbox-tools-2.0.19.jar  
xmpbox-2.0.19.jar  
preflight-2.0.19.jar  
fontbox-2.0.19.jar  
easytable-0.6.5.jar  
pdfbox2-layout-1.0.0.jar

**Comment by vandeseer** [comment]
Thanks for reporting. I will have a look as soon as I find a bit of time for that. Note though that the whole integration of `pdfbox-layout` is rather experimental, so it is more or less to be expected that not everything runs flawlessly ...

**Comment by vandeseer** [comment]
Fixed now with version 0.6.6
