### ISSUE TITLE
borderWidth is not working for table builder

### ISSUE THREAD

**Issue by stanleyfl88** [vandeseer/easytable#89]
borderWidth is not working for table builder.

Table myTable = Table.builder().addColumnsOfWidth(100, 100).borderWidth(1f)   --> not working

**Comment by vandeseer** [comment]
Yep, you are right. Thanks for reporting. 

It's simply not implemented yet but exposed already in the builder. I will fix this as soon as I find time for it. In the meantime you can just workaround by setting it accordingly on every cell.

**Comment by vandeseer** [comment]
Fixed in version 0.7.0
