### ISSUE TITLE
Vertical Alignment within a row (Feature)

### ISSUE THREAD

**Issue by Kevinschmid86** [vandeseer/easytable#9]
Hey vandeseer, 
many thanks for your little project. At the moment I´m trying to use the easytable for the first time. I need to create a table over several pages and with pdfarcform in it. 

I played around with your .setWordBreaking() function. It would be great if it would be possible to use a vertical alignment within a row, if the wordbreaking feature is used. 

I attached an image regarding this topic. 

Best regards

Kevin

![vertical_align](https://user-images.githubusercontent.com/12447078/47479887-cb8e5c80-d82e-11e8-8f46-37cd255cf0be.JPG)

**Comment by vandeseer** [comment]
Hi @Kevinschmid86, 
I am currently working on vertical alignment, just checkout this branch: feature/verticalAlignment
It's not yet merged to master and may still have issues. But just give it a shot and let me know if you experience any problems with it. If so, it would be very helpful if you could also provide me with a minimum working example, or not working example to be precise ;)

**Comment by vandeseer** [comment]
This is now part of version v0.1.0.
