### ISSUE TITLE
Extra rows doesn't create next page

### ISSUE THREAD

**Issue by stanleyfl88** [vandeseer/easytable#90]
Followed example from https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/MinimumWorkingExample.java

Added 30-40 more rows with height=4f, which suppose to have 2 pages of PDF.
But extra rows doesn't create next page, only 1 page available.

**Comment by vandeseer** [comment]
Please have a look here: https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/integrationtest/TableOverSeveralPagesTest.java
