### ISSUE TITLE
Text color customization within the cell

### ISSUE THREAD

**Issue by venkatdreddy** [vandeseer/easytable#92]
Is it possible to provide an option to change text color customization within the cell? It would be great if we can use different color for different text strings

**Comment by vandeseer** [comment]
Yes, that should be possible. Have a look at [this part in the README](https://github.com/vandeseer/easytable#paragraph-cells).

**Comment by venkatdreddy** [comment]
Thanks for your quick response. Sorry to miss the point "experimental: vertical text, links and paragraphs within cells".
